app:
  port: 3000
  host: '127.0.0.1'
dbs:
  db_nano: &db_nano
    type: 'nano-gierschv' # couchdb
    settings:
      url: 'http://localhost:5984/flat'
  db_mysql: &db_mysql
    type: 'mysql-gierschv'
    settings:
      host: 'localhost'
#      port: 8889
      database: 'flat'
      username: 'root'
      password: ''
  db_mongo: &db_mongo
    type: 'mongodb'
    settings:
      url: 'mongo://localhost/flat'
  # Sessions only
  db_redis: &db_redis
    type: 'redis'
    settings:
      host: 'localhost'
      port: 6379
  db_none: &db_memory
    type: 'memory'
db: *db_nano

cookie:
  secret: '352IbRsD71eur0y4RUj39xmDvnP1QXAnSPT9cySrQCs5iaAfy3D9cSgsX4f7XTi2LoDduDFC03xpgCCNp4V1Lm52JQuDJSPQBEQDCVjXGE0iWmbz3pinzN8YmPbFdpLg'
  path: '/'
session:
  key: 'flat.sid'
  secret: 'qGNhmR73fr6Wv6bmBD6a9v0XSE2QBgPWNQ1FpsogEiXIGMa8hRK9KKzD2dzKa0dsby8DrJs8hA6q7ixAeVbeW4RLgiRfm43LE2GBqGXP2oF1MchFGrx3wEPiGwvJ5FId'
  store: *db_redis