dbs:
  db_nano-gierschv: &db_nano-gierschv
    type: 'nano-gierschv' # couchdb
    settings:
      url: 'http://localhost:5984/flat-test'
  db_mysql-gierschv: &db_mysql-gierschv
    type: 'mysql-gierschv'
    settings:
      host: 'localhost'
      database: 'flattest'
      username: 'travis'
      password: ''
  db_none: &db_memory
    type: 'memory'
db: *db_nano-gierschv

# Fill with value
social:
#  twitter:
#    secret: ''
#    key: ''
#    callback: 'http://localhost:3000/auth/twitter/return'
  facebook:
    id: ''
    secret: ''
    callback: 'http://localhost:3000/auth/facebook/return'       
  google:
    id: ''
    secret: ''
    callback: 'http://127.0.0.1:3000/auth/google/return'       

cookie:
  secret: 'flat-test'
  path: '/'
session:
  key: 'flat.sid'
  secret: 'flat.sid-test'
  store: *db_memory
flat:
  score_storage: './tests/tmp'