dbs:
  db_nano-gierschv: &db_nano-gierschv
    type: 'nano-gierschv' # couchdb
    settings:
      url: 'http://localhost:5984/flat-test'
  db_mysql-gierschv: &db_mysql-gierschv
    type: 'mysql-gierschv'
    settings:
      host: 'localhost'
      database: 'flattest'
      username: 'travis'
      password: ''
  db_none: &db_memory
    type: 'memory'
db: *db_nano-gierschv

cookie:
  secret: 'flat-test'
  path: '/'
session:
  key: 'flat.sid'
  secret: 'flat.sid-test'
  store: *db_memory
flat:
  score_storage: './tests/tmp'

social:
 twitter:
   secret: '42'
   key: '42'
 facebook:
   id: '42'
   secret: '42'
 google:
   id: '42.apps.googleusercontent.com'
   secret: '42'

socketio:
  log_level: 0